### ISSUE TITLE
Introduce Cilium kube-proxy replacement

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#1825]
## What

Add L4LB with Cilium kube-proxy replacement

## How

- Add cilium manifest
  - Enable kubeProxyReplacement strict mode, XDP acceleration, dsr mode and MetalLB integration
  - Add MetallLB Configuration for each environment, GCP, stage-0, osaka-0 and tokyo-0 
- Disable kube-proxy
- Add tests to verify the Cilium L4LB feature

helm option
```
helm template cilium cilium/cilium --version 1.11.0 \
  --namespace=kube-system \
  --set rollOutCiliumPods=true \
  --set devices='{eth+,eno+}' \
  --set nodePort.directRoutingDevice=e+ \
  --set cni.chainingMode=generic-veth \
  --set cni.customConf=true \
  --set datapathMode=veth \
  --set tunnel=disabled \
  --set enableIPv4Masquerade=false \
  --set enableIdentityMark=true \
  --set kubeProxyReplacement=strict \
  --set loadBalancer.acceleration=native \
  --set loadBalancer.mode=dsr \
  --set hostServices.hostNamespaceOnly=true \
  --set loadBalancer.algorithm=maglev \
  --set bgp.enabled=true \
  --set bgp.announce.loadbalancerIP=true \
  --set k8sServiceHost=127.0.0.1 \
  --set k8sServicePort=16443
```

MetalLB configuration on GCP
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 127.0.0.1
        peer-asn: 64699
        my-asn: 64698
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 10.72.32.0/20
      - name: bastion
        protocol: bgp
        addresses:
          - 10.72.48.48/28
        auto-assign: false
      - name: internet
        protocol: bgp
        addresses:
          - 172.19.0.16/28
        auto-assign: false
```

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions
