### ISSUE TITLE
Tenant NetworkPolicy Controller

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#1878]
## What

We're going to constraint tenant users not to be able to send packets to other namespaces by default and require them to add network policies that allow communication with other namespaces as needed. During the transition period, we let tenant users choose to opt-in default-deny at egress. Also, we need to protect tenant users from accidentally granting access to the system networks such as bmc and node.

## How

Develop tenant network policy controller

- Provide opt-in default-deny at egress
- Prohibit tenant users not to allow the system networks such as bmc and node

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by Hsn723** [comment]
@ysksuzuki Here's the proposed design for the tenant NetworkPolicy controller, tentatively named `tenet`. Let me know what you think.

# Tenet
Tenet(tentative) is a Kubernetes controller that aims to facilitate setting-up Network Policies on tenant namespaces.

It is designed to work in conjunction with [Cilium Network Policies](https://docs.cilium.io/en/stable/policy/) and [Accurate](https://cybozu-go.github.io/accurate/).

## Motivation
To enhance the security without sacrificing convenience, we want to provide default network policies for tenants to consume. For instance, we want egress communications to be disabled by default in tenant namespaces. Tenants should be able to add exceptions to fit the needs of their workflows while being prevented from adding exceptions that are too broad, i.e. grant access to `node` resources.

## Usage
Tenet provides two custom resources to cluster administrators: `NetworkPolicyTemplate` and `NetworkPolicyAdmissionRule`.

### NetworkPolicyTemplate
`NetworkPolicyTemplate` enables administrators to write `CiliumNetworkPolicy` templates that tenants can opt-into via the `tenet.cybozu.io/network-policy-template` annotation in their `Namespace` resources. Templates can be supplied with values sources from the `.metadata` field of the `Namespace` resource that reference them. When annotations are placed on a root namespace managed by Accurate the annotations, and thus the templated CiliumNetworkPolicies, can be propagated to child namespaces. For instance, given the following `NetworkPolicyTemplate`,

```yaml
# network-policy-template.yaml
apiVersion: tenet.cybozu.io/v1beta1
kind: NetworkPolicyTemplate
metadata:
    name: allow-intra-namespace-egress
spec:
    policyTemplate: |
      apiVersion: cilium.io/v2
      kind: CiliumNetworkPolicy
      metadata:
        name: allow-intra-namespace-egress
      spec:
        endpointSelector: {}
        egress:
        - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": {{.namespace}}
```

When a tenant namespace is annotated like below,

```yaml
# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
annotations:
    tenet.cybozu.io/network-policy-template: allow-intra-namespace-egress
labels:
    accurate.cybozu.com/type: root
```

The following `CiliumNetworkPolicy` gets created in the `my-namespace` namespace:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-intra-namespace-egress
  namespace: my-namespace
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - matchLabels:
         "k8s:io.kubernetes.pod.namespace": my-namespace
```

Since `my-namespace` is an Accurate root namespace, any of its child namespace will inherit the `tenet.cybozu.io/network-policy-template` annotation and CiliumNetworkPolicies will be created with the templates filled-in.

### NetworkPolicyAdmissionRule
To restrict the scope of whitelist permissions tenants can write via CiliumNetworkPolicies or NetworkPolicies, cluster administrators can write `NetworkPolicyAdmissionRule` resources. This allows administrators to forbid the use of specific CIDR ranges as endpoint selectors for network policies. For instance, the following `NetworkPolicyAdmissionRule` will reject network policies in namespaces having the `team: hoge` label from specifing IP addresses within the 10.72.16.0/20 range for egress rules.

```yaml
# admission-rule.yaml
apiVersion: tenet.cybozu.io/v1beta1
kind: NetworkPolicyAdmissionRule
metadata:
    name: forbid-bmc
spec:
    namespaceSelector:
      matchLabels:
        team: hoge
    forbiddenIPRanges:
      - cidr: 10.72.16.0/20
        type: egress
```

IP address restrictions can be applied on ingress or egress type network policies. When no `type` is specified, the restrictions apply to both ingress and egress.
