### ISSUE TITLE
[CKE] configurable ratio of servers by their roles

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#377]
## What

Enhance sabakan integration feature so that users can specify the ratio of
servers in the cluster by their roles.

## How

- Enhance template of sabakan integration so that multiple non-control plane nodes can be defined.
- Each node in the template can declare `cke.cybozu.com/role` in the labels.
- Each non-control plane node in the template can declare `cke.cybozu.com/weight` in the labels.

An example template YAML looks like:

```yaml
nodes:
 - user: cybozu
   control_plane: true
   labels:
     cke.cybozu.com/role: cs
 - user: cybozu
   control_plane: false
   labels:
     cke.cybozu.com/role: cs
     cke.cybozu.com/weight: "6.0"
 - user: cybozu
   control_plane: false
   labels:
     cke.cybozu.com/role: ss
     cke.cybozu.com/weight: "3.0"
   taints:
   - key: cke.cybozu.com/role
     value: storage
     effect: NoExecute
```

With this template, sabakan integration chooses nodes as follows:
- control plane nodes are chosen from servers whose roles are "cs".
- 6 out of (6+3) non-control plane nodes are chosen from servers whose roles are "cs".
- 3 out of (6+3) non-control plane nodes are chosen from servers whose roles are "ss".
    - "ss" nodes will have a taint whose key is `cke.cybozu.com/role`, value is `storage`, and effect is `NoExecute`.

A template node w/o `cke.cybozu.com/role` label matches servers of any role.

A template node w/o `cke.cybozu.com/weight` label is regarded to have weight 1.0.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions
