### ISSUE TITLE
neco: downgrade artifacts

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#562]
## What

Currently, `generate-artifacts` always choose the latest container image on `quay.io`.
It is not possible to downgrade an artifact temporarily because generating `artifacts_release.go`
is completely automated.

Design and implement a way to downgrade artifacts whose latest images have critical problems.

## How

Add a config file to ignore specific versions.

By using `artifacts_ignore.yaml`, the latest versions of components can be ignored.
Use this, for example, if you have a bug in the latest versions and do not want to include it in `artifacts.go`.

```yaml
images:
- name: cke
  versions: ["1.2.3", "1.2.4", "1.2.5"]
- name: etcd
  versions: ["1.2.3.4"]
debs:
- name: etcdpasswd
  versions: ["v1.2.3"]
coreOS:
- channel: stable
  versions: ["2247.5.0"]
```

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions
