### ISSUE TITLE
Rook/Ceph: MON on PVC PoC

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#628]
## What

Rook/Ceph: Persistent /var/lib/rook

## How

Try anything.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by masa213f** [comment]
It works.

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 5Gi
        storageClassName: topolvm-provisioner
```
