### ISSUE TITLE
[neco][k8s 1.19]: Create scheduler profile for OSD pod

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#990]
## What

Create a scheduler profile for OSD pods on Kubernetes v1.19 for the following reasons.

- Disable `NodeResourcesBallancedAllocation` because the setting is suggested in the [issue of upstream](https://github.com/kubernetes/kubernetes/issues/91234#issuecomment-634706336).
- However, if you set that for `default-scheduler`, it will affect other Pods as well.
- Use the [Multiple profiles](https://kubernetes.io/docs/reference/scheduling/profiles/#multiple-profiles) feature to apply the setting of disabling `NodeResourcesBallancedAllocation` to OSD pods only.

## How

- Apply it for Kubernetes 1.19 or later because the weight of the scheduler has been adjusted.
- Before applying it, confirm that the osd pod will spread by disabling `BalancedResourceAllocation`.
- We can confirm that without multiple profiles by adjusting the weight of `default-scheduler` like below.

```
apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        disabled:
        - name: NodeResourcesBallancedAllocation
```

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions
