### ISSUE TITLE
Image registry mirror

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#993]
## Description

- Implement a pull-through mirror of container image registries on Kubernetes.

## Initiative / Motivation

To make applications on Kubernetes reliable, container images need to be always available.
However, neither Docker Hub nor quay.io can run without failures.

Having a pull-through mirror in the data center can resolve the problem.

## Technical information

Harbor 2.1 add pull-through cache feature.
https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/

[docker/distribution](https://github.com/docker/distribution)'s `registry` has an implementation of pull-through cache, but the feature is limited to a single remote registry only.
This limitation may be worked around by having two `registry` instances; one for Docker Hub, and the other for quay.io.

https://github.com/docker/docker.github.io/blob/master/registry/recipes/mirror.md#run-a-registry-as-a-pull-through-cache

## Scope and goal

Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

- MUST mirror registries under `quay.io/cybozu/` including private ones.

Non-scopes:

- Automatically pull images on `quay.io/cybozu` and `ghcr.io/cybozu` and `ghcr.io/cybozu-go` to mirror the necessary images.

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree on making this ready.

**Comment by zoetrope** [comment]
# PoC

## Deploy Docker Registry

Deploy the following manifests:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-repository-k8s
  namespace: registry
  labels:
    app: private-repository-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-repository-k8s
  template:
    metadata:
      labels:
        app: private-repository-k8s
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
      - name: registry-vol
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: registry-config
        configMap:
          name: registry-config
      containers:
        - image: registry:2
          name: private-repository-k8s
          imagePullPolicy: IfNotPresent
          command:
          - /bin/registry
          - serve
          - /etc/docker/registry/config.yml
          env:
          - name: HTTP_PROXY
            value: http://squid.internet-egress.svc:3128
          - name: HTTPS_PROXY
            value: http://squid.internet-egress.svc:3128
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: registry-vol
            mountPath: /var/lib/registry
          - name: registry-config
            mountPath: "/etc/docker/registry"
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |-
    version: 0.1
    log:
      level: debug
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    proxy:
      remoteurl: https://quay.io
```

```
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
spec:
  selector:
    app: private-repository-k8s
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pvc
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: topolvm-provisioner
```

## Modify containerd configuration

SSH to `10.69.1.133`.

Add the IP-Address of docker-registry service to the mirror endpoint in `/etc/k8s-containerd/config.toml`:

```
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
          endpoint = ["http://10.68.224.249:5000", "https://quay.io/"]
```

Add the IP-Address as NO_PROXY in `/etc/systemd/system/k8s-containerd.service`:

```
Environment="NO_PROXY=10.68.224.249"
```

Restart containerd:

```
sudo systemctl daemon-reload
sudo systemctl restart k8s-containerd
```

## Pull-through Mirror

Deploy the following manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: 10.69.1.133
      containers:
      - name: ubuntu
        image: quay.io/cybozu/ubuntu-debug:18.04
        imagePullPolicy: Always
        command: ["/usr/local/bin/pause"]
```

You can see the pull-through in the docker-registry log and the containerd log.
The first one will be pulling from upstream, the second one will be pulling from the docker-registry.

## Fallback

Stop the docker-registry pod and deploy the above ubuntu pod again. (Delete the image beforehand.)
You can see the fallback in the containerd log.

## Fallback private container

Create a secret from username and token:
```
kubectl create secret docker-registry regcred --docker-server=quay.io --docker-username=<ACCOUNT> --docker-password=<TOKEN>
```

Deploy the following manifest (it's using private container: `quay.io/ikezoe/cybozu-mysql:latest`)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: 10.69.1.133
      imagePullSecrets:
        - name: regcred
      containers:
      - name: mysql
        image: quay.io/ikezoe/cybozu-mysql:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/pause"]
```

In this case, pull-through will fail. (The credential will not be through)
However, the fallback will succeed in pulling from upstream.

## Pull-through private container

Configure the ConfigMap for docker-registry. Add `username` and `password` for private containers:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |-
    version: 0.1
    log:
      level: debug
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    proxy:
      remoteurl: https://quay.io
      username: <ACCOUNT>
      password: <TOKEN>
```

Deploy the above mysql pod again. (Delete the image beforehand.)
The private container image will be pulled by pull-through.
